version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "3002:3001"
    volumes:
      - ./backend/uploads:/usr/src/app/uploads
      - ./backend/database.db:/usr/src/app/database.db

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend 